# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigmoidAct <- function(X) {
    .Call('esmote_sigmoidAct', PACKAGE = 'esmote', X)
}

#' It's for backpropagation, the input X is actFun(X)
sigmoidGrad <- function(X) {
    .Call('esmote_sigmoidGrad', PACKAGE = 'esmote', X)
}

reluAct <- function(X) {
    .Call('esmote_reluAct', PACKAGE = 'esmote', X)
}

#' It's for backpropagation, the input X is actFun(X)
reluGrad <- function(X) {
    .Call('esmote_reluGrad', PACKAGE = 'esmote', X)
}

tanhAct <- function(X) {
    .Call('esmote_tanhAct', PACKAGE = 'esmote', X)
}

#' It's for backpropagation, the input x is actFun(x)
tanhGrad <- function(X) {
    .Call('esmote_tanhGrad', PACKAGE = 'esmote', X)
}

#' Multiply a number by two
#'
#' @param x A single integer.
timesTwo <- function(x) {
    .Call('esmote_timesTwo', PACKAGE = 'esmote', x)
}

